### ISSUE TITLE
angle measure

### ISSUE THREAD

**Issue by talmazov** [egtwobits/mesh_mesh_align_plus#7]
![mesh align plus](https://user-images.githubusercontent.com/46112624/58440758-7fe4af80-80aa-11e9-859e-84e42d5898dc.PNG)

How is it that this angle is 176.98 degrees? the lines are only a few degrees from parallel, am I setting this up wrong or is this a bug?

**Comment by egtwobits** [comment]
The angle is determined by the selection order of the verts on each line (in this case I know it's not what you're expecting so maybe it's worth adding a feature that will get the smaller number you're looking for).

The current solution: If you draw a point_A and point_B on the left edge and the right edge, the A's in your example will be on opposite ends (that's why the angle is really big). Enter edit mode (in vertex select), then shift + click start and endpoints, then hit grab all for that line (S. Grab Slot 1 or 2 in this example).

**Comment by egtwobits** [comment]
@talmazov Any additional thoughts here? Going to close this one out soon.
